version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - .:/app
    environment:
      - DB_URL=postgresql+psycopg2://postgres:postgres@db:5432/muhni
      - QDRANT_URL=http://qdrant:6333
    ports:
      - "8000:8000"
    depends_on:
      - db
      - qdrant

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    volumes:
      - .:/app
    environment:
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: muhni
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:v1.9.3
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

volumes:
  qdrant_data:
